services:
  #PHP Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: nongdev/inventory-backend:latest
    container_name: inventory_backend
    restart: unless-stopped
    tty: true
    env_file:
      - ./backend/.env
    working_dir: /var/www/html/
    volumes:
        # - ./backend/.env:/var/www/html/.env
        - backend_storage:/var/www/html/storage
        - ./backend/bootstrap/cache:/var/www/html/bootstrap/cache
    networks:
      - app-network
    depends_on:
      - db
    command: >
      sh -c "chown -R www-data:www-data storage bootstrap/cache &&
           chmod -R 775 storage bootstrap/cache &&
           php-fpm"
  

  frontend:
    stdin_open: true
    container_name: inventory_frontend
    image: nongdev/inventory-frontend:latest
    # env_file:
    #   - ./frontend/.env
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/dist:/var/www/html 
    # volumes:
    #   - /app/node_modules
    #   - ./frontend:/var/www/html/
    networks:
      - app-network

  # FastAPI AI Service
  ai:
    build:
      context: ./inventory_ai
      dockerfile: Dockerfile
    image: nongdev/inventory-ai:latest
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - db


  #Nginx Service
  # webserver:
  #   depends_on:
  #     - backend
  #     - frontend
  #     - ai
  #   build:
  #     context: ./backend/nginx
  #     dockerfile: Dockerfile
  #   image: nongdev/inventory-webserver:latest
  #   container_name: inventory_webserver
  #   restart: unless-stopped
  #   tty: true
  #   ports:
  #     - "82:82"
  #   volumes:
  #     - ./backend/public:/var/www/html:ro 
  #   networks:
  #     - app-network
    # Caddy Webserver
    webserver:
      container_name: inventory_webserver
      image: caddy:2.8.6-alpine
      restart: unless-stopped
      ports:
        - "82:80"        # temporary testing on port 82
        - "443:443"      # future SSL
      networks:
        - app-network
      volumes:
        - ./Caddyfile:/etc/caddy/Caddyfile:ro
        - ./backend/public:/var/www/html
        - caddy_data:/data
        - caddy_config:/config
      depends_on:
        - backend
        - frontend
        - ai
  db:
    image: postgres:15
    container_name: inventory_postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: inventory_management_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Docker Volumes
volumes:
    # backend_vendor:
    backend_storage:
    postgres_data:
    caddy_data:
    caddy_config:
