services:
  backend:
    image: nongdev/inventory-backend:latest
    restart: always
    networks:
      - web
    env_file:
      - ./backend/.env
    volumes:
      - backend_storage:/var/www/html/storage
      - ./backend/bootstrap/cache:/var/www/html/bootstrap/cache
    depends_on:
      - db
    command: >
      sh -c "chown -R www-data:www-data storage bootstrap/cache &&
             chmod -R 775 storage bootstrap/cache &&
             php-fpm"
  backend-caddy:
    image: caddy:2-alpine
    container_name: backend-caddy
    restart: always
    depends_on:
      - backend
    networks:
      - web
    volumes:
      - ./backend/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "8080:80"
  frontend:
    build:
      context: ./frontend
    image: nongdev/inventory-frontend:latest
    restart: always
    networks:
      - web

  ai:
    build:
      context: ./inventory_ai
    image: nongdev/inventory-ai:latest
    restart: always
    networks:
      - web
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: inventory_postgres_db
    restart: always
    environment:
      POSTGRES_DB: inventory_management_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - web

networks:
  web:
    external: true

volumes:
  backend_storage:
  postgres_data:
